development:
  adapter: mysql2
  database: pttfood
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"

# test:
#   adapter: mysql2
#   database: novel_server
#   host: 127.0.0.1
#   encoding: utf8
#   username: root
#   password: "db"

production:
  adapter: mysql2
  database: pttfood
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"
